"""add gravatar

Revision ID: 80ddcf07f733
Revises: a953d0e7ff8a
Create Date: 2018-10-12 14:04:26.295372

"""

# revision identifiers, used by Alembic.
revision = '80ddcf07f733'
down_revision = 'a953d0e7ff8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
