"""add field body_html in post

Revision ID: c9520331bef3
Revises: 89a51e749769
Create Date: 2018-10-16 15:51:25.640954

"""

# revision identifiers, used by Alembic.
revision = 'c9520331bef3'
down_revision = '89a51e749769'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
